---
- name: Deploy Nginx Knative Service
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition: "{{ lookup('template', '../templates/hello.yaml.j2') | from_yaml }}"

- name: Get the Knative Service list
  shell: "kn service list"
  register: service_list

- name: Print the Knative Service list
  debug:
    msg: "{{ service_list.stdout }}"
